### ISSUE TITLE
Errors when running example code

### ISSUE THREAD

**Issue by bsonghao** [dwavesystems/dwave-cloud-client#158]
When I tried to run the example 
code given on my PC, it return
this error:
Traceback (most recent call last):
  File "D_wave_example.py", line 8, in <module>
    solver = client.get_solver()
  File "/home/bsonghao/dwave-cloud-client/dwave/cloud/client.py", line 655, in get_solver
    raise SolverAuthenticationError
dwave.cloud.exceptions.SolverAuthenticationError: Token not accepted for that action.

**Comment by randomir** [comment]
Hey @bsonghao, looks like you're missing a default solver in your configuration (either `dwave.conf` file, or keyword arguments to `from_config()`).
If you don't know the name of the solver upfront, you can use `Client.get_solvers()` and then just use the one you need (first).

**Comment by randomir** [comment]
Oh, yes, the problem is with the `token` you're missing.

At the moment if you like a token to run problems on the quantum computer system you should contact sales@dwavesys.com.

However, not too long in the future we should be making it easier to get access and run simple tests on our quantum computer systems. Stay tuned! :-)

**Comment by bsonghao** [comment]
Got it. Thanks for your help.
