### ISSUE TITLE
Conflicts with dwave-preprocessing because both install /usr/local/lib/python3.9/site-packages/dwave/__init__.py

### ISSUE THREAD

**Issue by yurivict** [dwavesystems/dwave-cloud-client#531]

**Comment by yurivict** [comment]
ttps://github.com/dwavesystems/dwave-preprocessing/issues/45

**Comment by arcondello** [comment]
Hi @yurivict , dwave-system, dwave-cloud-client, dwave-preprocessing, dwave-drivers, dwave-samplers, etc are all namespace packages. Specifically [package-util style](https://packaging.python.org/en/latest/guides/packaging-namespace-packages/#pkgutil-style-namespace-packages).

**Comment by yurivict** [comment]
But they conflict with each other because they all install the same file.

**Comment by arcondello** [comment]
This is intentional. It allows all of those individually installed packages to share the same `dwave` namespace. That's also why the file is identical in all of them. See [namespace packages](https://packaging.python.org/en/latest/guides/packaging-namespace-packages/). At some point in the future we may switch to using [native namespace packages](https://packaging.python.org/en/latest/guides/packaging-namespace-packages/#native-namespace-packages) which does not require an `__init__.py`, but since we first started using them when we still supported Python 2, we still use the [pkgutil-style](https://packaging.python.org/en/latest/guides/packaging-namespace-packages/#pkgutil-style-namespace-packages).

**Comment by yurivict** [comment]
In such case the correct structure would be to have one base package that installs ```__init__.py``` and then have any number of other packages that depend on it which don't install ```__init__.py```.

Package managers reject file conflicts - such packages can't be installed at the same time.

**Comment by arcondello** [comment]
Our supported package installer, [pip](https://packaging.python.org/en/latest/guides/tool-recommendations/), handles the conflict by creating the following structure:
```
site-packages/
    dwave/
        cloud/
        preprocessing/
        system/
        __init__.py
```
I believe it keeps the first installed `__init__.py` from that namespace and ignores subsequent ones, but I would need to go deeper into the docs to confirm which `__init__.py` is used.

**Comment by yurivict** [comment]
What would happen if these files would be different? Would one of them be ignored? This would lead to a breakage.

**Comment by arcondello** [comment]
If they were different then yes, many would be ignored. Which is why we keep them identical, as required by the [docs I linked above](https://packaging.python.org/en/latest/guides/packaging-namespace-packages/#pkgutil-style-namespace-packages). Relevant section:
```
Every distribution that uses the namespace package must include an identical __init__.py. If any distribution does not, it will cause the namespace logic to fail and the other sub-packages will not be importable. Any additional code in __init__.py will be inaccessible.
```
