### ISSUE TITLE
When should I invoke the close method for the connection object?

### ISSUE THREAD

**Issue by arcondello** [dwavesystems/dwave-cloud-client#7]

**Comment by randomir** [comment]
You should call `close()` on `Client` instance (ex. `Connection`) as soon as you're done using the client, i.e. **as soon as you obtain the result (samples) from SAPI**.

Calling `close()` will release all allocated resources (several thread pools) which would not be garbage collected otherwise, but released to system only on program exit. Not following this rule becomes an issue if multiple (as in dozens) clients are instantiated, each one having its own thread pool.

The preferred way of using the `Client` is **via context manager** (refer to examples for details):
```
with Client(...) as client:
    solver = client.get_solver()
    future = solver.sample_ising(...)
    samples = future.result()
```
Note that **future** returned by sampling method on `Solver` **must be resolved** before closing the client (and killing thread pool workers), otherwise you will not be able to obtain the results.
